#!/bin/bash

echo "🔐 GitHub Actions Secrets Setup Guide"
echo "====================================="
echo ""
echo "This script helps you set up the required secrets for GitHub Actions."
echo "Please follow these steps in your GitHub repository:"
echo ""
echo "1. Go to your GitHub repository"
echo "2. Click Settings → Secrets and variables → Actions"
echo "3. Click 'New repository secret' for each of the following:"
echo ""
echo "📋 Required Secrets:"
echo ""
echo "• DEPLOY_HOST"
echo "  Description: Your server IP address or hostname"
echo "  Example: 192.168.1.100 or your-domain.com"
echo ""
echo "• DEPLOY_USER"
echo "  Description: SSH username for deployment"
echo "  Example: deploy or ubuntu"
echo ""
echo "• DEPLOY_KEY"
echo "  Description: SSH private key for server access"
echo "  How to generate: ssh-keygen -t rsa -b 4096 -C 'github-actions'"
echo "  Add the public key to your server's ~/.ssh/authorized_keys"
echo ""
echo "• SLACK_WEBHOOK (Optional)"
echo "  Description: Slack webhook URL for notifications"
echo "  How to get: Create Slack app and enable Incoming Webhooks"
echo ""
echo "🚀 Quick Setup Commands:"
echo ""
echo "# Generate SSH key pair"
echo "ssh-keygen -t rsa -b 4096 -C 'github-actions' -f ~/.ssh/github-actions"
echo ""
echo "# Copy public key to server"
echo "ssh-copy-id -i ~/.ssh/github-actions.pub user@your-server.com"
echo ""
echo "# Display private key (copy this to DEPLOY_SECRET)"
echo "cat ~/.ssh/github-actions"
echo ""
echo "🔍 Testing Setup:"
echo ""
echo "After setting up secrets, test the workflows by:"
echo "1. Pushing to a feature branch (triggers tests only)"
echo "2. Merging to develop (triggers full CI pipeline)"
echo "3. Merging to main (triggers deployment)"
echo ""
echo "📝 Notes:"
echo "- Ensure your server has PHP, Composer, and MySQL installed"
echo "- The deployment script assumes /var/www/laravel-api as deployment path"
echo "- Modify deploy.yml if your setup differs"
echo ""
echo "✅ Setup complete! Your GitHub Actions are ready to run."
